-- BrassTune baseline schema for a clean Supabase Postgres database.
-- The FastAPI backend mediates app access; direct Data API policies stay closed
-- until browser-to-table access is intentionally designed.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  supabase_user_id text unique,
  username text unique,
  name text not null,
  display_name text,
  email text,
  role text not null default 'student',
  primary_instrument_id text not null default 'trumpet',
  onboarding_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_supabase_user_id on public.users (supabase_user_id);
create index if not exists ix_users_username on public.users (username);
create index if not exists ix_users_email on public.users (email);

create table if not exists public.instrument_profiles (
  id text primary key,
  name text not null,
  transposition_semitones integer not null,
  min_frequency_hz double precision not null,
  max_frequency_hz double precision not null,
  metadata_json text not null default '{}'
);

create table if not exists public.practice_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  instrument_id text not null,
  name text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds double precision not null default 0,
  reference_pitch_hz double precision not null default 440,
  notes_count integer not null default 0,
  average_signed_cents double precision not null default 0,
  average_abs_cents double precision not null default 0,
  in_tune_percentage double precision not null default 0,
  audio_storage_provider text,
  audio_object_key text,
  audio_mime_type text,
  audio_duration_seconds double precision,
  audio_size_bytes integer,
  audio_uploaded_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists ix_practice_sessions_user_id on public.practice_sessions (user_id);
create index if not exists ix_practice_sessions_instrument_id on public.practice_sessions (instrument_id);
create index if not exists ix_practice_sessions_started_at on public.practice_sessions (started_at);

create table if not exists public.pitch_samples (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.practice_sessions(id) on delete cascade,
  timestamp_ms integer not null,
  frequency_hz double precision not null,
  confidence double precision not null,
  rms double precision not null,
  concert_midi_float double precision not null,
  concert_nearest_midi integer not null,
  concert_note text not null,
  concert_octave integer not null,
  written_midi integer not null,
  written_note text not null,
  written_octave integer not null,
  cents_deviation double precision not null,
  tuning_status text not null,
  is_valid_for_recording integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists ix_pitch_samples_session_id on public.pitch_samples (session_id);
create index if not exists ix_pitch_samples_created_at on public.pitch_samples (created_at);

create table if not exists public.note_events (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.practice_sessions(id) on delete cascade,
  instrument_id text not null,
  written_note text not null,
  written_octave integer not null,
  concert_note text not null,
  concert_octave integer not null,
  started_at_ms integer not null,
  ended_at_ms integer not null,
  duration_ms integer not null,
  sample_count integer not null,
  avg_signed_cents double precision not null,
  avg_abs_cents double precision not null,
  median_cents double precision not null,
  stddev_cents double precision not null,
  min_cents double precision not null,
  max_cents double precision not null,
  in_tune_percentage double precision not null,
  stability_score double precision not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_note_events_session_id on public.note_events (session_id);
create index if not exists ix_note_events_instrument_id on public.note_events (instrument_id);
create index if not exists ix_note_events_written_note on public.note_events (written_note, written_octave);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  director_user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_groups_director_user_id on public.groups (director_user_id);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  instrument_id text not null,
  role_in_group text not null default 'student',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique (group_id, user_id)
);

create index if not exists ix_group_members_group_id on public.group_members (group_id);
create index if not exists ix_group_members_user_id on public.group_members (user_id);
create index if not exists ix_group_members_status on public.group_members (status);

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  invited_username text not null,
  invited_user_id bigint references public.users(id) on delete set null,
  invited_by_user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  accepted_at timestamptz
);

create index if not exists ix_invitations_group_id on public.invitations (group_id);
create index if not exists ix_invitations_invited_username on public.invitations (invited_username);
create index if not exists ix_invitations_status on public.invitations (status);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  session_id bigint references public.practice_sessions(id) on delete cascade,
  note_event_id bigint references public.note_events(id) on delete cascade,
  written_note text,
  written_octave integer,
  severity text not null,
  title text not null,
  message text not null,
  suggestions_json text not null default '[]',
  created_at timestamptz not null default now()
);

create index if not exists ix_recommendations_user_id on public.recommendations (user_id);
create index if not exists ix_recommendations_session_id on public.recommendations (session_id);
create index if not exists ix_recommendations_note_event_id on public.recommendations (note_event_id);

alter table public.users enable row level security;
alter table public.instrument_profiles enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.pitch_samples enable row level security;
alter table public.note_events enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.invitations enable row level security;
alter table public.recommendations enable row level security;
