-- BrassTune production-readiness migration scaffold.
-- Apply to a Supabase Postgres project after reviewing table exposure settings.
-- Supabase changed new-table Data API exposure behavior in 2026; grant exposed
-- schema access deliberately and keep RLS enabled for every public table.

alter table if exists public.users
  add column if not exists supabase_user_id text unique,
  add column if not exists username text unique,
  add column if not exists display_name text,
  add column if not exists email text,
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists updated_at timestamptz default now();

alter table if exists public.practice_sessions
  add column if not exists audio_storage_provider text,
  add column if not exists audio_object_key text,
  add column if not exists audio_mime_type text,
  add column if not exists audio_duration_seconds double precision,
  add column if not exists audio_size_bytes integer,
  add column if not exists audio_uploaded_at timestamptz;

alter table if exists public.groups
  add column if not exists updated_at timestamptz default now();

alter table if exists public.group_members
  add column if not exists role_in_group text default 'student',
  add column if not exists status text default 'active';

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  invited_username text not null,
  invited_user_id bigint references public.users(id) on delete set null,
  invited_by_user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  accepted_at timestamptz
);

alter table if exists public.users enable row level security;
alter table if exists public.practice_sessions enable row level security;
alter table if exists public.pitch_samples enable row level security;
alter table if exists public.note_events enable row level security;
alter table if exists public.groups enable row level security;
alter table if exists public.group_members enable row level security;
alter table if exists public.invitations enable row level security;

-- Storage bucket, if the storage schema is available to this migration runner.
insert into storage.buckets (id, name, public)
values ('session-audio', 'session-audio', false)
on conflict (id) do update set public = false;

-- BrassTune currently routes authenticated app data through FastAPI, which uses
-- server-side Supabase validation. Keep direct Data API policies conservative
-- until direct browser-to-table access is intentionally designed.
