-- Lightweight product-usage tracking: a last-active stamp on users plus a
-- coarse usage_events table. The FastAPI backend is the only writer (via the
-- pooled DB connection); RLS stays enabled and the Data API stays closed.

alter table public.users
  add column if not exists last_active_at timestamptz;

create index if not exists idx_users_last_active_at
  on public.users(last_active_at);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_usage_events_created_at
  on public.usage_events(created_at);

create index if not exists idx_usage_events_name_created_at
  on public.usage_events(event_name, created_at);

create index if not exists idx_usage_events_user_id
  on public.usage_events(user_id);

alter table public.usage_events enable row level security;
